export const USER_VEHICLE_SLOT = "USER_VEHICLE_SLOT";
export const USER_VEHICLE_SLOT_PENDING = "USER_VEHICLE_SLOT_PENDING";
export const VEHICLE_DROP_PENDING = "VEHICLE_DROP_PENDING";
export const USER_VEHICLE_ERROR = "USER_VEHICLE_ERROR";
