export const GARAGES = "GARAGES";
export const GARAGES_GET_PENDING = "GARAGES_GET_PENDING";
export const GARAGE_DETAIL = "GARAGE_DETAIL";
export const GARAGE_DETAIL_PENDING = "GARAGE_DETAIL_PENDING";
export const VEHICLE_BOOK_PENDING = "VEHICLE_BOOK_PENDING";
export const GARAGE_ERROR = "GARAGE_ERROR";
